$DEFAULT_DB_URL="jdbc:sqlserver://localhost:1433"
$DEFAULT_DB_USER="dont us sa"
$DEFAULT_DB_PASS="demouser"

#Location of the i2b2 web services
$DEFAULT_I2B2_SERVICE_URL="http://localhost:9090/i2b2/services"
$PM_SERVICE_URL="$DEFAULT_I2B2_SERVICE_URL/PMService/getServices"
$CRC_SERVICE_URL="$DEFAULT_I2B2_SERVICE_URL/QueryToolService"
$FR_SERVICE_URL="$DEFAULT_I2B2_SERVICE_URL/FRService"

#Service account used by i2b2 software
$I2B2_SERVICEACCOUNT_USER="AGG_SERVICE_ACCOUNT"
$I2B2_SERVICEACCOUNT_PASS="demouser"


$HIVE_DB_URL=$DEFAULT_DB_URL
$HIVE_DB_USER="i2b2hive"
$HIVE_DB_PASS=$DEFAULT_DB_PASS

$PM_DB_URL=$DEFAULT_DB_URL
$PM_DB_USER="i2b2pm"
$PM_DB_PASS=$DEFAULT_DB_PASS


$ONT_METADATA_DB_SCHEMA="i2b2metadata.dbo"
$ONT_DB_URL=$DEFAULT_DB_URL
$ONT_DB_USER="i2b2metadata"
$ONT_DB_PASS=$DEFAULT_DB_PASS

