   -- I2b2 1.5 convention: Holds the SHRINE Ontology Table
   CREATE TABLE SHRINE 
   (
    "C_HLEVEL" NUMBER(22,0),
	"C_FULLNAME" VARCHAR2(900), 
	"C_NAME" VARCHAR2(2000), 
	"C_SYNONYM_CD" CHAR(1), 
	"C_VISUALATTRIBUTES" CHAR(3), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(450), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50), 
	"C_TABLENAME" VARCHAR2(50), 
	"C_COLUMNNAME" VARCHAR2(50), 
	"C_COLUMNDATATYPE" VARCHAR2(50), 
	"C_OPERATOR" VARCHAR2(10), 
	"C_DIMCODE" VARCHAR2(900), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(900), 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50), 
	"VALUETYPE_CD" VARCHAR2(50),
        "M_APPLIED_PATH" VARCHAR2(900),
        "M_EXCLUSION_CD" VARCHAR2(900)
   ) ;

  -- I2b2 1.5 convention: Governs access to the SHRINE Ont table
  CREATE TABLE TABLE_ACCESS
   (
    "C_TABLE_CD" VARCHAR2(50),
	"C_TABLE_NAME" VARCHAR2(50), 
	"C_PROTECTED_ACCESS" CHAR(1),
	"C_HLEVEL" NUMBER(22,0), 
	"C_FULLNAME" VARCHAR2(900), 
	"C_NAME" VARCHAR2(2000), 
	"C_SYNONYM_CD" CHAR(1), 
	"C_VISUALATTRIBUTES" CHAR(3), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(450), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50), 
	"C_DIMTABLENAME" VARCHAR2(50), 
	"C_COLUMNNAME" VARCHAR2(50), 
	"C_COLUMNDATATYPE" VARCHAR2(50), 
	"C_OPERATOR" VARCHAR2(10), 
	"C_DIMCODE" VARCHAR2(900), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(900), 
	"C_ENTRY_DATE" DATE, 
	"C_CHANGE_DATE" DATE, 
	"C_STATUS_CD" CHAR(1), 
	"VALUETYPE_CD" VARCHAR(50)
   ) ;

   -- TODO: not sure how this is actually loaded up
   CREATE TABLE  "SCHEMES"
   (
    "C_KEY" VARCHAR2(50) NOT NULL ENABLE,
	"C_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"C_DESCRIPTION" VARCHAR2(100),
	 CONSTRAINT "SCHEMES_PK" PRIMARY KEY ("C_KEY") ENABLE
   )
   ;



