insert into ONT_DB_LOOKUP
(C_DOMAIN_ID, C_PROJECT_PATH, C_OWNER_ID, C_DB_FULLSCHEMA, C_DB_DATASOURCE, C_DB_SERVERTYPE, C_DB_NICENAME)
VALUES
('I2B2_DOMAIN_ID','SHRINE/','@','I2B2_DB_SHRINE_ONT_USER','java:/I2B2_DB_SHRINE_ONT_DATASOURCE_NAME','POSTGRESQL','SHRINE');

-- TODO: schema work for crc lookup?
insert into CRC_DB_LOOKUP
(C_DOMAIN_ID, C_PROJECT_PATH, C_OWNER_ID, C_DB_FULLSCHEMA, C_DB_DATASOURCE, C_DB_SERVERTYPE, C_DB_NICENAME)
VALUES
( 'I2B2_DOMAIN_ID', '/SHRINE/', '@', 'public', 'java:/I2B2_DB_CRC_DATASOURCE_NAME', 'POSTGRESQL', 'SHRINE' );
